language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t alejovillegas7/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true alejovillegas7/react-test npm test 

after_success:
    - docker build -t $DOCKERHUB_USER/multi-client ./client 
    - docker build -t $DOCKERHUB_USER/multi-nginx ./nginx 
    - docker build -t $DOCKERHUB_USER/multi-server ./server 
    - docker build -t $DOCKERHUB_USER/multi-worker ./worker 
    #Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login "$DOCKER_ID" --password-stdin
    #take those images and push them to docker hub
    - docker push $DOCKERHUB_USER/multi-client
    - docker push $DOCKERHUB_USER/multi-nginx
    - docker push $DOCKERHUB_USER/multi-server
    - docker push $DOCKERHUB_USER/multi-worker 

